### ISSUE TITLE
Generated code is blank ..

### ISSUE THREAD

**Issue by ASACHIT** [Proxlight/Proxlight-Designer#2]
**it generates Code just only with Background color... everything is blank** 😥😭😭
![image](https://user-images.githubusercontent.com/73944456/128984793-a739d59b-a9a6-4691-a698-10f7f3b1f449.png)

**Comment by Proxlight** [comment]
Set x and 

> **it generates Code just only with Background color... everything is blank** 😥😭😭
> ![image](https://user-images.githubusercontent.com/73944456/128984793-a739d59b-a9a6-4691-a698-10f7f3b1f449.png)

**Comment by Proxlight** [comment]
Set x and y value to zero in figma

**Comment by ath34-tech** [comment]
Even after setting x and y to zero it is still giving blank

**Comment by Proxlight** [comment]
Around 1000 people are using this tool and they are getting no errors so why do you have such issues, by the way, watch the updated tutorial carefully, don't miss any step

**Comment by ath34-tech** [comment]
> Around 1000 people are using this tool and they are getting no errors so why do you have such issues, by the way, watch the updated tutorial carefully, don't miss any step

Yes, the mistake was in my own design, it is solved now.
