### ISSUE TITLE
Token?

### ISSUE THREAD

**Issue by Didward** [Proxlight/Proxlight-Designer#5]
I used the installation from the website (not Github) and I am not sure what to put here. I thought I had to look at my receipt and paste something from there - I couldn't find anything. I was confused when watching the video because it didn't have much detail. It only told me that it's where you put your token. Please help.
![image](https://user-images.githubusercontent.com/86981999/166899609-00d7dce8-08ad-4961-a901-13033664e1b3.png)

**Comment by Proxlight** [comment]
Take token from figma account for clarity witch youtube video.
